export const CONSCIOUS_OPTION = [
    { value: 'An Giang', label: 'An Giang'},
    { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu'},
    { value: 'Bạc Liêu', label: 'Bạc Liêu'},
    { value: 'Bắc Giang', label: 'Bắc Giang'},
    { value: 'Bắc Kạn', label: 'Bắc Kạn'},
    { value: 'Bắc Ninh', label: 'Bắc Ninh'},
    { value: 'Bến Tre', label: 'Bến Tre'},
    { value: 'Bình Dương', label: 'Bình Dương'},
    { value: 'Bình Định', label: 'Bình Định'},
    { value: 'Bình Phước', label: 'Bình Phước'},
    { value: 'Bình Thuận', label: 'Bình Thuận'},
    { value: 'Cà Mau', label: 'Cà Mau'},
    { value: 'Cao Bằng', label: 'Cao Bằng'},
    { value: 'Cần Thơ', label: 'Cần Thơ'},
    { value: 'Đà Nẵng', label: 'Đà Nẵng'},
    { value: 'Đắk Lắk', label: 'Đắk Lắk'},
    { value: 'Đắk Nông', label: 'Đắk Nông'},
    { value: 'Điện Biên', label: 'Điện Biên'},
    { value: 'Đồng Tháp', label: 'Đồng Tháp'},
    { value: 'Gia Lai', label: 'Gia Lai'},
    { value: 'Hà Giang', label: 'Hà Giang'},
    { value: 'Hà Nam', label: 'Hà Nam'},
    { value: 'Hải Phòng', label: 'Hải Phòng'},
    { value: 'Hải Dương', label: 'Hải Dương'},
    { value: 'Hà Tĩnh', label: 'Hà Tĩnh'},
    { value: 'Hà Nội', label: 'Hà Nội'},
    { value: 'Hưng Yên', label: 'Hưng Yên'},
    { value: 'Hồ Chí Minh', label: 'Hồ Chí Minh'},
    { value: 'Hòa Bình', label: 'Hòa Bình'},
    { value: 'Hậu Giang', label: 'Hậu Giang'},
    { value: 'Lai Châu', label: 'Lai Châu'},
    { value: 'Kon Tum', label: 'Kon Tum'},
    { value: 'Kiên Giang', label: 'Kiên Giang'},
    { value: 'Khánh Hòa', label: 'Khánh Hòa'},
    { value: 'Long An', label: 'Long An'},
    { value: 'Lâm Đồng', label: 'Lâm Đồng'},
    { value: 'Lào Cai', label: 'Lào Cai'},
    { value: 'Lạng Sơn', label: 'Lạng Sơn'},
    { value: 'Ninh Thuận', label: 'Ninh Thuận'},
    { value: 'Ninh Bình', label: 'Ninh Bình'},
    { value: 'Nghệ An', label: 'Nghệ An'},
    { value: 'Nam Định', label: 'Nam Định'},
    { value: 'Quảng Nam', label: 'Quảng Nam'},
    { value: 'Quảng Bình', label: 'Quảng Bình'},
    { value: 'Phú Yên', label: 'Phú Yên'},
    { value: 'Phú Thọ', label: 'Phú Thọ'},
    { value: 'Sóc Trăng', label: 'Sóc Trăng'},
    { value: 'Quảng Trị', label: 'Quảng Trị'},
    { value: 'Quảng Ninh', label: 'Quảng Ninh'},
    { value: 'Quảng Ngãi', label: 'Quảng Ngãi'},
    { value: 'Thái Nguyên', label: 'Thái Nguyên'},
    { value: 'Thái Bình', label: 'Thái Bình'},
    { value: 'Tây Ninh', label: 'Tây Ninh'},
    { value: 'Sơn La', label: 'Sơn La'},
    { value: 'Trà Vinh', label: 'Trà Vinh'},
    { value: 'Tiền Giang', label: 'Tiền Giang'},
    { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế'},
    { value: 'Thanh Hóa', label: 'Thanh Hóa'},
    { value: 'Yên Bái', label: 'Yên Bái'},
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc'},
    { value: 'Vĩnh Long', label: 'Vĩnh Long'},
    { value: 'Tuyên Quang', label: 'Tuyên Quang'},
]
export const CATEGORY_OPTION = [
    { value: 'ĐỊA ĐIỂM', label: 'ĐỊA ĐIỂM'},
    { value: 'ẨM THỰC', label: 'ẨM THỰC'},
    { value: 'HOMETAY', label: 'HOMESTAY'},
    { value: 'CẨM NANG', label: 'CẨM NANG'},
]